[uv]
requirements = "requirements.txt"

[uv.index]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[uv.cache]
dir = "./.uv/cache"

[uv.venv]
dir = "./venv"

[uv.python]
implementation = "cpython"
version = "3.11"

[uv.install]
no-binary = false
no-deps = false